# Generated by Django 5.2 on 2025-04-23 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Аллергия', 'verbose_name_plural': 'Аллергии'},
        ),
        migrations.AlterModelOptions(
            name='diet',
            options={'verbose_name': 'Диета', 'verbose_name_plural': 'Диеты'},
        ),
        migrations.AlterModelOptions(
            name='foodintake',
            options={'verbose_name': 'Приём пищи', 'verbose_name_plural': 'Приёмы пищи'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='typeofmenu',
            options={'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
        migrations.AlterModelOptions(
            name='typeofsubscription',
            options={'verbose_name': 'Тип подписки', 'verbose_name_plural': 'Типы подписок'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Аллергия'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='foodintake',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Приём пищи'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_of_ingredients',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='allergy',
            field=models.ManyToManyField(related_name='orders', to='recepies.allergy', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_intake',
            field=models.ManyToManyField(related_name='orders', to='recepies.foodintake', verbose_name='Приёмы пищи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_people',
            field=models.IntegerField(default=1, verbose_name='Количество персон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.userprofile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_menu',
            field=models.ManyToManyField(related_name='orders', to='recepies.typeofmenu', verbose_name='Типы меню'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.typeofsubscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergy',
            field=models.ManyToManyField(related_name='recipes', to='recepies.allergy', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(related_name='recipes', to='recepies.diet', verbose_name='Диеты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food_intake',
            field=models.ManyToManyField(related_name='recipes', to='recepies.foodintake', verbose_name='Приёмы пищи'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recepies.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='liked_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type_of_menu',
            field=models.ManyToManyField(related_name='recipes', to='recepies.typeofmenu', verbose_name='Типы меню'),
        ),
        migrations.AlterField(
            model_name='typeofmenu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='typeofsubscription',
            name='period',
            field=models.IntegerField(verbose_name='Период (дней)'),
        ),
        migrations.AlterField(
            model_name='typeofsubscription',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='users', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
