# Generated by Django 5.2 on 2025-04-26 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите действительный email адрес', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email адрес'),
        ),
    ]
