# Generated by Django 5.2 on 2025-04-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipes',
            field=models.ManyToManyField(related_name='orders', to='recepies.recipe', verbose_name='Рецепты'),
        ),
    ]
