# Generated by Django 5.2 on 2025-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_alter_allergy_options_alter_diet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='breakfasts',
            field=models.BooleanField(default=False, verbose_name='Завтрак включён'),
        ),
        migrations.AddField(
            model_name='order',
            name='desserts',
            field=models.BooleanField(default=False, verbose_name='Десерт включён'),
        ),
        migrations.AddField(
            model_name='order',
            name='dinners',
            field=models.BooleanField(default=False, verbose_name='Ужин включён'),
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.IntegerField(default=False, verbose_name='Длительность подписки'),
        ),
        migrations.AddField(
            model_name='order',
            name='lunches',
            field=models.BooleanField(default=False, verbose_name='Ужин включён'),
        ),
        migrations.AddField(
            model_name='typeofsubscription',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название подписки'),
        ),
    ]
