# Generated by Django 5.2 on 2025-04-29 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_order_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recepies.diet', verbose_name='Диеты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
